FROM ghost:3.3.0

LABEL Name=ghost-test Version=3.3.0

COPY ./ghost/3.3.0/content /var/lib/ghost/content

RUN apt-get update && \
    apt-get install iputils-ping -y

EXPOSE 3002

CMD node current/index.js